### ISSUE TITLE
Not on https://plugins.lapce.dev?

### ISSUE THREAD

**Issue by haroldallen** [doupkg/lapcord#6]
Why is this epic plugin not on plugins.lapce.dev?
I want to install it but I don't know how to do it myself, so just add it to their thing and then it can do it for me!

Literally why not I added my theme there in like 30m.

Looks cool anyway

**Comment by jesus-ale43** [comment]
we are fixing some things to upload it 👾

**Comment by haroldallen** [comment]
great feel free to close issue when you have uploaded it (do @ping me tho so i can download lol)

**Comment by jesus-ale43** [comment]
https://plugins.lapce.dev/plugins/Hyduez/dou.lapcord
