### ISSUE TITLE
Folders with spaces in their name display with %20

### ISSUE THREAD

**Issue by haroldallen** [doupkg/lapcord#8]
Hi, sorry to make yet another issue lol.  
Just a small visual one this time, nothing plugin-breaking.  
Folders with spaces in their name display with %20.  
  
**Proposed solution:**  
(name).replace('%20', ' ') in JS
Since plugins are written in Rust I have no idea.

**Comment by haroldallen** [comment]
![image](https://user-images.githubusercontent.com/67546646/230439965-9e11490a-5a6f-4ca7-b4ae-06c945700419.png)
Here's a screenshot

Unrelated: time to make you idle is very short, should be a minute or so.

**Comment by jesus-ale43** [comment]
You can make a pull request in https://github.com/doupkg/lapcord-server

**Comment by jesus-ale43** [comment]
This is where the RPC is handled

**Comment by hyduez** [comment]
I have fixed it, thank you.
<br />
![](https://i.imgur.com/Y3bHMw6.png)
